### ISSUE TITLE
PATCH /projects/:id/

### ISSUE THREAD

**Issue by zildj** [senior-design-marketplace/express-typescript-server#14]
**Description:** Error when patching a title that is 64<x<257

**Verb:** Patch

**Path:** `/projects/:id/`

**Body:**
>{"title": "1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 "}

**Response:** 500
>DataError: update "projects" set "title" = $1 where "projects"."id" = $2 - value too long for type character varying(64)
    at wrapError (/var/task/node_modules/db-errors/lib/dbErrors.js:19:14)
    at handleExecuteError (/var/task/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1494:32)
    at QueryBuilder.execute (/var/task/node_modules/objection/lib/queryBuilder/QueryBuilder.js:685:13)

**Comment by mfreema1** [comment]
Seems to be an inconsistency between request validation logic and the underlying DB logic.  Will be an easy fix.

**Comment by mfreema1** [comment]
Going to let this go for a little bit.  Will likely perform an audit of our table and validation layer soon to ensure that they conform to each other.
